DECL_GL_PROC(BlendColor, glBlendColor, PFNGLBLENDCOLORPROC)
DECL_GL_PROC(BlendEquation, glBlendEquation, PFNGLBLENDEQUATIONPROC)
DECL_GL_PROC(DrawRangeElements, glDrawRangeElements, PFNGLDRAWRANGEELEMENTSPROC)
DECL_GL_PROC(TexImage3D, glTexImage3D, PFNGLTEXIMAGE3DPROC)
DECL_GL_PROC(TexSubImage3D, glTexSubImage3D, PFNGLTEXSUBIMAGE3DPROC)
DECL_GL_PROC(CopyTexSubImage3D, glCopyTexSubImage3D, PFNGLCOPYTEXSUBIMAGE3DPROC)

